[server]
maxUploadSize = 4500
address = "127.0.0.1"
headless = false
baseUrlPath = ""

[theme]
base = "light"
primaryColor = "#6A1B3F"
backgroundColor = "#F6F4F5"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1F1F1F"
font = "sans serif"


[client]
showSidebarNavigation = false
toolbarMode = "minimal"

[browser]
serverAddress = "localhost"
serverPort = 8501
gatherUsageStats = false
